const {Events}=require('discord.js');const config=require('../config');const {getDb,ensureGuild}=require('../database');const {chat}=require('../services/ai');const {checkCooldown}=require('../utils/cooldown');const {logGuild}=require('../services/logging');
async function logModeration(g,text){await logGuild(g,'AutoMod',text)}module.exports={name:Events.MessageCreate,execute:async(m)=>{if(!m.guild||m.author.bot)return;ensureGuild(m.guild.id);const db=getDb();
const rules=db.prepare('SELECT * FROM moderation_rules WHERE guild_id=?').get(m.guild.id);
if(rules){
  const recentKey=`spam:${m.guild.id}:${m.author.id}`;
  const gate=checkCooldown(recentKey,5000);
  if(rules.anti_flood && !gate){ /* token bucket reset is handled by cooldown */ }
  if(rules.anti_invite && /(discord\.gg\/|discord(?:app)?\.com\/invite\/)/i.test(m.content)){ await m.delete().catch(()=>{}); await logModeration(m.guild,`Invite removed from ${m.author.tag}`); return; }
  if(rules.anti_link && /https?:\/\//i.test(m.content) && !m.member.permissions.has('ManageMessages')){ await m.delete().catch(()=>{}); await logModeration(m.guild,`Link removed from ${m.author.tag}`); return; }
  const bad=(rules.bad_words||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean); if(bad.some(w=>m.content.toLowerCase().includes(w))){ await m.delete().catch(()=>{}); await logModeration(m.guild,`Bad word removed from ${m.author.tag}`); return; }
  if(m.mentions.users.size + m.mentions.roles.size > (rules.mention_limit||8) && !m.member.permissions.has('ManageMessages')){ await m.delete().catch(()=>{}); await logModeration(m.guild,`Mention flood removed from ${m.author.tag}`); return; }
}
const custom=db.prepare('SELECT response FROM custom_commands WHERE guild_id=? AND name=?').get(m.guild.id,(m.content.startsWith(config.prefix)?m.content.slice(config.prefix.length).trim().split(/\s+/)[0].toLowerCase():''));
if(custom && m.content.startsWith(config.prefix)){ await m.reply(custom.response).catch(()=>{}); return; }
if(!m.content.startsWith(config.prefix)){const gate=checkCooldown(`xp:${m.guild.id}:${m.author.id}`,60000);let u=db.prepare('SELECT * FROM users WHERE guild_id=? AND user_id=?').get(m.guild.id,m.author.id);if(!u){db.prepare('INSERT INTO users(guild_id,user_id,xp,level,balance) VALUES(?,?,?,?,?)').run(m.guild.id,m.author.id,10,0,0)}else if(!gate){const rate=db.prepare('SELECT xp_rate FROM guild_settings WHERE guild_id=?').get(m.guild.id)?.xp_rate||1;const xp=u.xp+Math.max(1,Math.round(10*rate)),lvl=Math.floor(xp/100);db.prepare('UPDATE users SET xp=?,level=? WHERE guild_id=? AND user_id=?').run(xp,lvl,m.guild.id,m.author.id);if(lvl>u.level)m.channel.send(`🎉 <@${m.author.id}> reached **Level ${lvl}**!`).catch(()=>{});}}
if(m.mentions.everyone&&!config.allowMassMentions)return;if(m.content.startsWith(config.prefix)){const a=m.content.slice(config.prefix.length).trim().split(/\s+/),name=a.shift()?.toLowerCase();if(name==='ai'&&a.length){const cd=checkCooldown(`ai:${m.guild.id}:${m.author.id}`,config.ai.userCooldownMs);if(cd)return m.reply(`⏳ Try again in ${Math.ceil(cd/1000)}s.`);try{await m.channel.sendTyping();const r=await chat({guildId:m.guild.id,userId:m.author.id,prompt:a.join(' ')});await m.reply(r.slice(0,1900));}catch(e){await m.reply(`❌ ${e.message}`).catch(()=>{});}}}
for(const a of db.prepare('SELECT * FROM autoresponders WHERE guild_id=?').all(m.guild.id)){if(a.channel_id&&a.channel_id!==m.channel.id)continue;const src=a.case_sensitive?m.content:m.content.toLowerCase(),tr=a.case_sensitive?a.trigger:a.trigger.toLowerCase();let match=false;if(a.mode==='exact')match=src===tr;else if(a.mode==='regex'){try{match=new RegExp(a.trigger,a.case_sensitive?'':'i').test(m.content)}catch{}}else match=src.includes(tr);if(match&&!checkCooldown(`auto:${a.id}:${m.author.id}`,a.cooldown_ms||0))await m.reply(a.response).catch(()=>{});}}
};
